language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: ZAn3ApPraqYcdJF+EedQNPMEcKTtHyMBV3Ga8tuiN+ce6XV5NvLHIOysTnTaHQy4fcdqH60Py2mSw4NjSv7w3RGQYJHgnz9P+2jEswioMESlo9VUrb4naBvSH2AlC1FLjrOLAbqDPFbv0AFYs4jsHYrUQbNJ7g9SeJ2XcUqfdFBDu1u6sQjehYefeZi/Jcpwqeh3h01bDeu6zRPgdqGYdasvrUAZFj1oJBd/PDH/MtPLupY/JLKCgH3y+rPj7PMfm7QwcM07WTdlR22uaUTaAocigYnfocmYp348LSY3cheQYtv9oVVjFzaW7q/32JC9J2oV2aGONA8YvW8VGFxMuFQqM/j/skoqQV1IkykwfQ3r921osQyO639YowGR319/Qwj4ndnzKuNVm/5DvXwfys9Gm9NXIAFXi+LW+9my/zbBBE+/hmhv+E/hOh3osqlX1jjVS/G8KxkjpODKqrQXCuA8agczGipS2qBIdpSDGUjCKvwZHnIaxZ34wSyIlwWuCG9LqNaAYtmKcpDUDLlYfYwHipJxZhS34i3s1yAnpW9pgdMDmtFsqXMBS65kFaG+5iWLSvD5r1godtxUylU9yKCddRML4n99l5zLHrAkUhQ/lj2taSiSM1PC+Un3Q0jHlrDmQMBNCWV2IIT9skMgAdtf9CORSBGt77UxJSzSsWI=
