# This is a configuration file for badges.
# When you create new badges add them here.
# Criteria field is an array of methods from app/models/badge_checker.rb.
# Be sure to add new criteria there when needed.

#development: &development
# In criteria, use these to create to create either a single or multi line string
# | for multi line string
# > for single line string

- badge: one plus one
  name: one point received
  criteria: 2 > 1
  
#- badge: 20 points received
  #name: third badge
  #criteria: 3 + 3 >= 6

#production:
#  <<: *development

#test:
#  <<: *development